### ISSUE TITLE
Prediction with unknown antigen

### ISSUE THREAD

**Issue by wu-yc** [tianshilu/pMTnet#10]
Hi Dr Tianshi,

Thanks for this beautiful work. It is really useful.

I have a list of HLA (HLA-A*02:01) and TCR CDR3 sequences (e.g. CAVLDSNYQLIW), but I don't know what the exact antigen is. Is there any possible solutions to compute the score of HLA-TCR match score?

Thanks again for your kind help.

Best,
Yingcheng

**Comment by tianshilu** [comment]
Hi @wu-yc ,

Thanks for your interest in our study. The current version of pMTnet is not able to make predictions without antigens. We are developing a more advanced version that would be able to do the task. 

Tianshi
