### ISSUE TITLE
Prediction with unknown HLA

### ISSUE THREAD

**Issue by wu-yc** [tianshilu/pMTnet#12]
Dear Tianshi,

I want to examine the connection between peptides and TCR, but without the related HLA information. Do you have any suggestions?

Thank you so much for your attention and help.
Yingcheng

**Comment by wtwt5237** [comment]
@wu-yc , theoretically, you can try to input your peptide, your TCR and every possible HLA into pMTnet, and then average over all HLAs (sort of like deriving the marginal distribution). But we haven't tested this approach before, and we are not sure whether it is good or not

**Comment by wu-yc** [comment]
@wtwt5237 Thanks so much for your helpful instructions.
