### ISSUE TITLE
TCR_encoder_30.h5 and other trained models in the repo

### ISSUE THREAD

**Issue by ravinpoudel** [tianshilu/pMTnet#3]
Is it possible to provide the code to generate 'TCR_encoder_30.h5' or other models that have been loaded in the repo?

**Comment by wtwt5237** [comment]
Hi, Ravinpoudel

The author who generated that part of the model passed away unexpectedly a few weeks ago. So it's a little hard to provide the codes of that part. I am really sorry about this.

Thanks!

Tao
