### ISSUE TITLE
Strange characters in the testing_data.csv and training_data.csv

### ISSUE THREAD

**Issue by Miles-DDD** [tianshilu/pMTnet#7]
hi, I find some strange characters in the datasets you provided for training and testing. For example, in the 30 and 31 row of testing_data.csv, the antigen sequence seems  to contain a strange Chinese word.

![a](https://user-images.githubusercontent.com/74239179/158817127-694bc539-3f40-4162-8edb-9066c22f90f0.png)

When I loaded this file with pandas, I found this character seems to be '\xa0'.
![image](https://user-images.githubusercontent.com/74239179/158950432-c02839bf-9698-4121-835f-6215664f9d2c.png)
So, is this a mistake made in generating the files or '\xa0' could have some special meaning?  Thank you.

**Comment by wtwt5237** [comment]
Hi @Miles-DDD 

I opened up the test data csv file online, and these are what I see:

CAWSETGLGMGGWQFG | ELAGIGILTV | A*02:01
CAWSETGLGTGELFFG | ELAGIGILTV | A*02:01

Is it possible that this strange character is caused by the downloading process (to your computer)?

Tao
